package com.example.ui.strings

import com.example.model.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        val dict = when (language) {
            AppLanguage.PT -> pt
            AppLanguage.EN -> en
            AppLanguage.ES -> es
        }
        return dict[key] ?: pt[key] ?: key
    }

    private val pt = mapOf(
        "app_name" to "Nexus Chat",
        "hello" to "Olá!",
        "welcome_subtitle" to "Comunicação de última geração com criptografia de ponta a ponta avançada, comunidades e Nexus IA.",
        "btn_login" to "Log in",
        "btn_enter_guest" to "Entrar sendo visitante",
        "login_dialog_title" to "Entrar no Nexus Chat",
        "login_phone_hint" to "Número de telefone (ex: +55 11 98765-4321)",
        "login_name_hint" to "Seu nome",
        "guest_badge" to "Visitante",
        "guest_no_profile" to "esse perfil não existe, faça login",
        "profile_login_prompt" to "Crie uma conta para personalizar foto, nome, banner e sincronizar suas conversas.",
        "tab_chats" to "Conversas",
        "tab_status" to "Status",
        "tab_feed" to "Social",
        "tab_ia" to "Nexus IA",
        "tab_settings" to "Ajustes",
        "filter_all" to "Todas",
        "filter_groups" to "Grupos",
        "filter_communities" to "Comunidades",
        "filter_calls" to "Ligações",
        "btn_add_person" to "Adicionar pessoa",
        "add_person_title" to "Adicionar Nova Pessoa",
        "add_person_phone_hint" to "Número de telefone da pessoa",
        "add_person_name_hint" to "Nome do contato (opcional)",
        "add_person_confirm" to "Iniciar Conversa",
        "btn_create_group" to "Criar grupo",
        "create_group_title" to "Criar Novo Grupo",
        "group_name_hint" to "Nome do grupo",
        "group_desc_hint" to "Descrição do grupo",
        "btn_create_community" to "Criar comunidade",
        "create_community_title" to "Criar Nova Comunidade",
        "community_name_hint" to "Nome da comunidade",
        "community_desc_hint" to "Objetivo ou descrição da comunidade",
        "encrypted_badge" to "Criptografia de ponta a ponta avançada",
        "encryption_security_note" to "As mensagens e chamadas deste chat estão protegidas com criptografia de ponta a ponta avançada. Ninguém fora desta conversa pode lê-las.",
        "type_message" to "Mensagem criptografada...",
        "audio_recording" to "Gravando áudio...",
        "audio_release_to_send" to "Solte para enviar",
        "voice_call" to "Ligação de voz",
        "video_call" to "Chamada de vídeo",
        "call_encrypted_notice" to "🔒 Chamada criptografada de ponta a ponta",
        "call_connecting" to "Conectando chamada segura...",
        "call_active" to "Chamada em andamento",
        "end_call" to "Encerrar",
        "status_ephemeral" to "Status Efêmeros (24h)",
        "status_public" to "Status Públicos",
        "status_my_status" to "Meu status",
        "status_tap_to_add" to "Toque para atualizar seu status",
        "status_add_title" to "Novo Status",
        "status_public_toggle" to "Publicar no Status Público",
        "status_views" to "visualizações",
        "social_feed_title" to "Postagens da Comunidade",
        "btn_create_post" to "Criar Publicação",
        "create_post_hint" to "O que você gostaria de compartilhar com o Nexus?",
        "create_post_tag_hint" to "Tag (ex: #Tecnologia, #NexusChat)",
        "btn_publish" to "Publicar",
        "post_likes" to "Curtidas",
        "post_comments" to "Comentários",
        "post_share" to "Compartilhar",
        "nexus_ia_title" to "Nexus IA",
        "nexus_ia_subtitle" to "Seu assistente inteligente para navegação e suporte",
        "nexus_ia_input_hint" to "Pergunte algo ou peça para navegar...",
        "settings_title" to "Configurações",
        "section_theme" to "Tema & Aparência",
        "theme_dark" to "Escuro",
        "theme_light" to "Claro",
        "theme_system" to "Padrão do Sistema",
        "section_language" to "Idioma do Aplicativo",
        "section_notifications" to "Configuração de Notificações",
        "notif_messages" to "Notificações de Mensagens",
        "notif_groups" to "Notificações de Grupos",
        "notif_calls" to "Notificações de Ligações",
        "notif_sound" to "Sons do aplicativo",
        "notif_vibrate" to "Vibração",
        "notif_preview" to "Pré-visualização de mensagens",
        "section_profile" to "Configuração de Perfil",
        "profile_name" to "Nome de perfil",
        "profile_phone" to "Número de telefone",
        "profile_photo" to "Mudar foto de perfil",
        "profile_banner" to "Mudar banner de perfil",
        "btn_save" to "Salvar Alterações",
        "cancel" to "Cancelar"
    )

    private val en = mapOf(
        "app_name" to "Nexus Chat",
        "hello" to "Hello!",
        "welcome_subtitle" to "Next-generation communication with advanced end-to-end encryption, communities, and Nexus AI.",
        "btn_login" to "Log in",
        "btn_enter_guest" to "Enter as visitor",
        "login_dialog_title" to "Log in to Nexus Chat",
        "login_phone_hint" to "Phone number (e.g. +1 555-0199)",
        "login_name_hint" to "Your name",
        "guest_badge" to "Visitor",
        "guest_no_profile" to "esse perfil não existe, faça login",
        "profile_login_prompt" to "Create an account to customize photo, name, banner and sync chats.",
        "tab_chats" to "Chats",
        "tab_status" to "Status",
        "tab_feed" to "Social",
        "tab_ia" to "Nexus AI",
        "tab_settings" to "Settings",
        "filter_all" to "All",
        "filter_groups" to "Groups",
        "filter_communities" to "Communities",
        "filter_calls" to "Calls",
        "btn_add_person" to "Add person",
        "add_person_title" to "Add New Person",
        "add_person_phone_hint" to "Person's phone number",
        "add_person_name_hint" to "Contact name (optional)",
        "add_person_confirm" to "Start Chat",
        "btn_create_group" to "Create group",
        "create_group_title" to "Create New Group",
        "group_name_hint" to "Group name",
        "group_desc_hint" to "Group description",
        "btn_create_community" to "Create community",
        "create_community_title" to "Create New Community",
        "community_name_hint" to "Community name",
        "community_desc_hint" to "Community purpose or description",
        "encrypted_badge" to "Advanced End-to-End Encryption",
        "encryption_security_note" to "Messages and calls in this chat are secured with advanced end-to-end encryption. No one outside this chat can read them.",
        "type_message" to "Encrypted message...",
        "audio_recording" to "Recording audio...",
        "audio_release_to_send" to "Release to send",
        "voice_call" to "Voice call",
        "video_call" to "Video call",
        "call_encrypted_notice" to "🔒 End-to-end encrypted call",
        "call_connecting" to "Connecting secure call...",
        "call_active" to "Call in progress",
        "end_call" to "End Call",
        "status_ephemeral" to "Ephemeral Status (24h)",
        "status_public" to "Public Status",
        "status_my_status" to "My status",
        "status_tap_to_add" to "Tap to update your status",
        "status_add_title" to "New Status",
        "status_public_toggle" to "Post to Public Status",
        "status_views" to "views",
        "social_feed_title" to "Community Posts",
        "btn_create_post" to "Create Post",
        "create_post_hint" to "What would you like to share on Nexus?",
        "create_post_tag_hint" to "Tag (e.g., #Tech, #NexusChat)",
        "btn_publish" to "Publish",
        "post_likes" to "Likes",
        "post_comments" to "Comments",
        "post_share" to "Share",
        "nexus_ia_title" to "Nexus AI",
        "nexus_ia_subtitle" to "Your smart assistant for navigation and support",
        "nexus_ia_input_hint" to "Ask anything or ask to navigate...",
        "settings_title" to "Settings",
        "section_theme" to "Theme & Appearance",
        "theme_dark" to "Dark",
        "theme_light" to "Light",
        "theme_system" to "System Default",
        "section_language" to "App Language",
        "section_notifications" to "Notification Settings",
        "notif_messages" to "Message Notifications",
        "notif_groups" to "Group Notifications",
        "notif_calls" to "Call Notifications",
        "notif_sound" to "In-app sounds",
        "notif_vibrate" to "Vibration",
        "notif_preview" to "Message previews",
        "section_profile" to "Profile Settings",
        "profile_name" to "Profile name",
        "profile_phone" to "Phone number",
        "profile_photo" to "Change profile photo",
        "profile_banner" to "Change profile banner",
        "btn_save" to "Save Changes",
        "cancel" to "Cancel"
    )

    private val es = mapOf(
        "app_name" to "Nexus Chat",
        "hello" to "¡Hola!",
        "welcome_subtitle" to "Comunicación de última generación con cifrado de extremo a extremo avanzado, comunidades y Nexus IA.",
        "btn_login" to "Log in",
        "btn_enter_guest" to "Entrar siendo visitante",
        "login_dialog_title" to "Iniciar sesión en Nexus Chat",
        "login_phone_hint" to "Número de teléfono (ej: +34 612 345 678)",
        "login_name_hint" to "Tu nombre",
        "guest_badge" to "Visitante",
        "guest_no_profile" to "esse perfil não existe, faça login",
        "profile_login_prompt" to "Crea una cuenta para personalizar foto, nombre, banner y sincronizar chats.",
        "tab_chats" to "Chats",
        "tab_status" to "Estados",
        "tab_feed" to "Social",
        "tab_ia" to "Nexus IA",
        "tab_settings" to "Ajustes",
        "filter_all" to "Todos",
        "filter_groups" to "Grupos",
        "filter_communities" to "Comunidades",
        "filter_calls" to "Llamadas",
        "btn_add_person" to "Adicionar pessoa",
        "add_person_title" to "Añadir Nueva Persona",
        "add_person_phone_hint" to "Número de teléfono de la persona",
        "add_person_name_hint" to "Nombre de contacto (opcional)",
        "add_person_confirm" to "Iniciar Chat",
        "btn_create_group" to "Criar grupo",
        "create_group_title" to "Crear Nuevo Grupo",
        "group_name_hint" to "Nombre del grupo",
        "group_desc_hint" to "Descripción del grupo",
        "btn_create_community" to "Criar comunidade",
        "create_community_title" to "Crear Nueva Comunidad",
        "community_name_hint" to "Nombre de la comunidad",
        "community_desc_hint" to "Propósito o descripción",
        "encrypted_badge" to "Cifrado avanzado de extremo a extremo",
        "encryption_security_note" to "Los mensajes y llamadas están protegidos con cifrado avanzado de extremo a extremo. Nadie fuera de este chat puede leerlos.",
        "type_message" to "Mensaje cifrado...",
        "audio_recording" to "Grabando audio...",
        "audio_release_to_send" to "Suelta para enviar",
        "voice_call" to "Llamada de voz",
        "video_call" to "Videollamada",
        "call_encrypted_notice" to "🔒 Llamada cifrada de extremo a extremo",
        "call_connecting" to "Conectando llamada segura...",
        "call_active" to "Llamada en curso",
        "end_call" to "Finalizar",
        "status_ephemeral" to "Estados Efímeros (24h)",
        "status_public" to "Estados Públicos",
        "status_my_status" to "Mi estado",
        "status_tap_to_add" to "Toca para actualizar tu estado",
        "status_add_title" to "Nuevo Estado",
        "status_public_toggle" to "Publicar en Estados Públicos",
        "status_views" to "vistas",
        "social_feed_title" to "Publicaciones de la Comunidad",
        "btn_create_post" to "Criar Publicação",
        "create_post_hint" to "¿Qué te gustaría compartir en Nexus?",
        "create_post_tag_hint" to "Etiqueta (ej: #Tecnología, #NexusChat)",
        "btn_publish" to "Publicar",
        "post_likes" to "Me gusta",
        "post_comments" to "Comentarios",
        "post_share" to "Compartir",
        "nexus_ia_title" to "Nexus IA",
        "nexus_ia_subtitle" to "Tu asistente inteligente para navegación y soporte",
        "nexus_ia_input_hint" to "Pregunta algo o pide navegar...",
        "settings_title" to "Configuraciones",
        "section_theme" to "Tema y Apariencia",
        "theme_dark" to "Oscuro",
        "theme_light" to "Claro",
        "theme_system" to "Predeterminado",
        "section_language" to "Idioma de la Aplicación",
        "section_notifications" to "Configuración de Notificaciones",
        "notif_messages" to "Notificaciones de Mensajes",
        "notif_groups" to "Notificaciones de Grupos",
        "notif_calls" to "Notificaciones de Llamadas",
        "notif_sound" to "Sonidos de la app",
        "notif_vibrate" to "Vibración",
        "notif_preview" to "Vista previa de mensajes",
        "section_profile" to "Configuración de Perfil",
        "profile_name" to "Nombre de perfil",
        "profile_phone" to "Número de teléfono",
        "profile_photo" to "Cambiar foto de perfil",
        "profile_banner" to "Cambiar banner de perfil",
        "btn_save" to "Guardar Cambios",
        "cancel" to "Cancelar"
    )
}
